# Generated by Django 5.0.8 on 2024-08-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_status', models.BooleanField(default=True)),
                ('Product_Serial_No', models.CharField(max_length=100)),
                ('Product_image', models.ImageField(upload_to='products/')),
                ('Product_Specification', models.TextField()),
                ('Product_description', models.CharField(max_length=100)),
                ('Product_created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
