# Generated by Django 5.0.7 on 2024-08-09 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Master', '0001_initial'),
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Product_Assigned_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='Product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.product_category'),
        ),
    ]
