# Generated by Django 5.0.7 on 2024-08-09 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Master', '0001_initial'),
        ('Products', '0002_initial'),
        ('email_templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='email_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.emailtemplatecategory'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.products'),
        ),
        migrations.AddField(
            model_name='emailattachment',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_templates.emailtemplate'),
        ),
    ]
