# Generated by Django 5.0.7 on 2024-08-10 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_templates', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailattachment',
            name='email_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_templates.emailtemplate'),
        ),
    ]
