# Generated by Django 5.0.7 on 2024-08-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-due_date',),
            },
        ),
    ]
