# Generated by Django 5.0.7 on 2024-08-09 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Lead', '0001_initial'),
        ('Master', '0001_initial'),
        ('Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.client_type'),
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_Industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.industry_type'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_followup_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.lead_followup_status'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.lead_source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.lead_status'),
        ),
        migrations.AddField(
            model_name='lead',
            name='products',
            field=models.ManyToManyField(blank=True, to='Products.products'),
        ),
    ]
