# Generated by Django 5.0.8 on 2024-08-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0005_alter_lead_first_name'),
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='client_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.clienttype'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_website',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_followup_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.leadfollowupstatus'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.industrytype'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.leadsource'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Master.leadstatus'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
