# Generated by Django 5.0.8 on 2024-08-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0008_rename_lead_folloup_status_followuptask_lead_followup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followuptask',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
